package core.classes.api.user;

import java.util.Date;

import org.hibernate.type.NullableType;

/**
 * AdminPermissionrequest generated by hbm2java
 */
public class AdminPermissionrequest implements java.io.Serializable {

	private Integer requestId;
	private AdminUser adminUserByApprover;
	private AdminUser adminUserByRequester;
	private String reqestPermission;
	private String reason;
	private java.sql.Date requestDate;
	private java.sql.Date approveDate;
	private boolean isActive;
	private Boolean isApprove;

	public AdminPermissionrequest() {
	}

	public AdminPermissionrequest(AdminUser adminUserByRequester,
			String reqestPermission, String reason, java.sql.Date requestDate,
			boolean isActive,boolean isApprove) {
		this.adminUserByRequester = adminUserByRequester;
		this.reqestPermission = reqestPermission;
		this.reason = reason;
		this.requestDate = requestDate;
		this.isActive = isActive;
		this.isApprove = isApprove;
	}

	public AdminPermissionrequest(AdminUser adminUserByApprover,
			AdminUser adminUserByRequester, String reqestPermission,
			String reason, java.sql.Date requestDate, java.sql.Date approveDate, boolean isActive, boolean isApprove) {
		this.adminUserByApprover = adminUserByApprover;
		this.adminUserByRequester = adminUserByRequester;
		this.reqestPermission = reqestPermission;
		this.reason = reason;
		this.requestDate = requestDate;
		this.approveDate = approveDate;
		this.isActive = isActive;
		this.isApprove = isApprove;
	}

	public Integer getRequestId() {
		return this.requestId;
	}

	public void setRequestId(Integer requestId) {
		this.requestId = requestId;
	}

	public AdminUser getAdminUserByApprover() {
		return this.adminUserByApprover;
	}

	public void setAdminUserByApprover(AdminUser adminUserByApprover) {
		this.adminUserByApprover = adminUserByApprover;
	}

	public AdminUser getAdminUserByRequester() {
		return this.adminUserByRequester;
	}

	public void setAdminUserByRequester(AdminUser adminUserByRequester) {
		this.adminUserByRequester = adminUserByRequester;
	}

	public String getReqestPermission() {
		return this.reqestPermission;
	}

	public void setReqestPermission(String reqestPermission) {
		this.reqestPermission = reqestPermission;
	}

	public String getReason() {
		return this.reason;
	}

	public void setReason(String reason) {
		this.reason = reason;
	}

	public java.sql.Date getRequestDate() {
		return this.requestDate;
	}

	public void setRequestDate(java.sql.Date requestDate) {
		this.requestDate = requestDate;
	}

	public java.sql.Date getApproveDate() {
		return this.approveDate;
	}

	public void setApproveDate(java.sql.Date approveDate) {
		this.approveDate = approveDate;
	}

	public boolean isIsActive() {
		return this.isActive;
	}

	public void setIsActive(boolean isActive) {
		this.isActive = isActive;
	}
	

	public Boolean getIsApprove() {
		return this.isApprove;
	}

	public void setIsApprove(Boolean isApprove) {
		this.isApprove = isApprove;
	}

}
