package core.classes.mri;

// default package
// Generated Apr 4, 2015 3:37:57 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * MriBundle generated by hbm2java
 */
public class MriBundle implements java.io.Serializable {

	private Integer bundleId;
	private MriHospital mriHospital;
	private Date requestDateTime;
	private int noOfRequests;
	private Set mriTestRequests = new HashSet(0);

	public MriBundle() {
	}

	public MriBundle(MriHospital mriHospital, Date requestDateTime,
			int noOfRequests) {
		this.mriHospital = mriHospital;
		this.requestDateTime = requestDateTime;
		this.noOfRequests = noOfRequests;
	}

	public MriBundle(MriHospital mriHospital, Date requestDateTime,
			int noOfRequests, Set mriTestRequests) {
		this.mriHospital = mriHospital;
		this.requestDateTime = requestDateTime;
		this.noOfRequests = noOfRequests;
		this.mriTestRequests = mriTestRequests;
	}

	public Integer getBundleId() {
		return this.bundleId;
	}

	public void setBundleId(Integer bundleId) {
		this.bundleId = bundleId;
	}

	public MriHospital getMriHospital() {
		return this.mriHospital;
	}

	public void setMriHospital(MriHospital mriHospital) {
		this.mriHospital = mriHospital;
	}

	public Date getRequestDateTime() {
		return this.requestDateTime;
	}

	public void setRequestDateTime(Date requestDateTime) {
		this.requestDateTime = requestDateTime;
	}

	public int getNoOfRequests() {
		return this.noOfRequests;
	}

	public void setNoOfRequests(int noOfRequests) {
		this.noOfRequests = noOfRequests;
	}

	public Set getMriTestRequests() {
		return this.mriTestRequests;
	}

	public void setMriTestRequests(Set mriTestRequests) {
		this.mriTestRequests = mriTestRequests;
	}

}
