package core.classes.mri;

// default package
// Generated Apr 4, 2015 3:37:57 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * MriDepartment generated by hbm2java
 */
public class MriDepartment implements java.io.Serializable {

	private Integer departmentId;
	private MriEmployee mriEmployee;
	private String departmentName;
	private String location;
	private Integer laboratoryCounts;
	private Integer numberOfMlt;
	private Integer numberOfConsultant;
	private Set mriLaboratories = new HashSet(0);
	private Set mriEmployeeWorkins = new HashSet(0);

	public MriDepartment() {
	}

	public MriDepartment(MriEmployee mriEmployee, String departmentName,
			String location,Integer laboratoryCounts, Integer numberOfMlt,
			Integer numberOfConsultant) {
		this.mriEmployee = mriEmployee;
		this.departmentName = departmentName;
		this.location = location;
		this.laboratoryCounts = laboratoryCounts;
		this.numberOfMlt = numberOfMlt;
		this.numberOfConsultant = numberOfConsultant;
	}

	public MriDepartment(MriEmployee mriEmployee, String departmentName,
			String location, Set mriLaboratories,
			Set mriEmployeeWorkins) {
		this.mriEmployee = mriEmployee;
		this.departmentName = departmentName;
		this.location = location;
		this.laboratoryCounts = laboratoryCounts;
		this.numberOfMlt = numberOfMlt;
		this.numberOfConsultant = numberOfConsultant;
		this.mriLaboratories = mriLaboratories;
		this.mriEmployeeWorkins = mriEmployeeWorkins;
	}

	public Integer getDepartmentId() {
		return this.departmentId;
	}

	public void setDepartmentId(Integer departmentId) {
		this.departmentId = departmentId;
	}

	public MriEmployee getMriEmployee() {
		return this.mriEmployee;
	}

	public void setMriEmployee(MriEmployee mriEmployee) {
		this.mriEmployee = mriEmployee;
	}

	public String getDepartmentName() {
		return this.departmentName;
	}

	public void setDepartmentName(String departmentName) {
		this.departmentName = departmentName;
	}

	public String getLocation() {
		return this.location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

	public Integer getLaboratoryCounts() {
		return this.laboratoryCounts;
	}

	public void setLaboratoryCounts(Integer laboratoryCounts) {
		this.laboratoryCounts = laboratoryCounts;
	}

	public Integer getNumberOfMlt() {
		return this.numberOfMlt;
	}

	public void setNumberOfMlt(Integer numberOfMlt) {
		this.numberOfMlt = numberOfMlt;
	}

	public Integer getNumberOfConsultant() {
		return this.numberOfConsultant;
	}

	public void setNumberOfConsultant(Integer numberOfConsultant) {
		this.numberOfConsultant = numberOfConsultant;
	}

	public Set getMriLaboratories() {
		return this.mriLaboratories;
	}

	public void setMriLaboratories(Set mriLaboratories) {
		this.mriLaboratories = mriLaboratories;
	}

	public Set getMriEmployeeWorkins() {
		return this.mriEmployeeWorkins;
	}

	public void setMriEmployeeWorkins(Set mriEmployeeWorkins) {
		this.mriEmployeeWorkins = mriEmployeeWorkins;
	}

}
