package core.classes.mri;

// default package
// Generated Apr 4, 2015 3:37:57 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * MriDesignation generated by hbm2java
 */
public class MriDesignation implements java.io.Serializable {

	private Integer designationId;
	private String designationName;
	private Set mriEmployeeWorkins = new HashSet(0);

	public MriDesignation() {
	}

	public MriDesignation(String designationName) {
		this.designationName = designationName;
	}

	public MriDesignation(String designationName, Set mriEmployeeWorkins) {
		this.designationName = designationName;
		this.mriEmployeeWorkins = mriEmployeeWorkins;
	}

	public Integer getDesignationId() {
		return this.designationId;
	}

	public void setDesignationId(Integer designationId) {
		this.designationId = designationId;
	}

	public String getDesignationName() {
		return this.designationName;
	}

	public void setDesignationName(String designationName) {
		this.designationName = designationName;
	}

	public Set getMriEmployeeWorkins() {
		return this.mriEmployeeWorkins;
	}

	public void setMriEmployeeWorkins(Set mriEmployeeWorkins) {
		this.mriEmployeeWorkins = mriEmployeeWorkins;
	}

}
