package core.classes.mri;

// default package
// Generated Apr 4, 2015 3:37:57 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * MriEmployeeWorkin generated by hbm2java
 */
public class MriEmployeeWorkin implements java.io.Serializable {

	private Integer employeeWorkinId;
	private MriDepartment mriDepartment;
	private MriLaboratory mriLaboratory;
	private MriDesignation mriDesignation;
	private MriEmployee mriEmployee;
	private Date startDate;
	private Date endDate;
	private String description;
	private boolean isActive;

	public MriEmployeeWorkin() {
	}

	public MriEmployeeWorkin(MriDepartment mriDepartment,
			MriLaboratory mriLaboratory, MriDesignation mriDesignation,
			MriEmployee mriEmployee, Date startDate, String description,
			boolean isActive) {
		this.mriDepartment = mriDepartment;
		this.mriLaboratory = mriLaboratory;
		this.mriDesignation = mriDesignation;
		this.mriEmployee = mriEmployee;
		this.startDate = startDate;
		this.description = description;
		this.isActive = isActive;
	}

	public MriEmployeeWorkin(MriDepartment mriDepartment,
			MriLaboratory mriLaboratory, MriDesignation mriDesignation,
			MriEmployee mriEmployee, Date startDate, Date endDate,
			String description, boolean isActive) {
		this.mriDepartment = mriDepartment;
		this.mriLaboratory = mriLaboratory;
		this.mriDesignation = mriDesignation;
		this.mriEmployee = mriEmployee;
		this.startDate = startDate;
		this.endDate = endDate;
		this.description = description;
		this.isActive = isActive;
	}

	public Integer getEmployeeWorkinId() {
		return this.employeeWorkinId;
	}

	public void setEmployeeWorkinId(Integer employeeWorkinId) {
		this.employeeWorkinId = employeeWorkinId;
	}

	public MriDepartment getMriDepartment() {
		return this.mriDepartment;
	}

	public void setMriDepartment(MriDepartment mriDepartment) {
		this.mriDepartment = mriDepartment;
	}

	public MriLaboratory getMriLaboratory() {
		return this.mriLaboratory;
	}

	public void setMriLaboratory(MriLaboratory mriLaboratory) {
		this.mriLaboratory = mriLaboratory;
	}

	public MriDesignation getMriDesignation() {
		return this.mriDesignation;
	}

	public void setMriDesignation(MriDesignation mriDesignation) {
		this.mriDesignation = mriDesignation;
	}

	public MriEmployee getMriEmployee() {
		return this.mriEmployee;
	}

	public void setMriEmployee(MriEmployee mriEmployee) {
		this.mriEmployee = mriEmployee;
	}

	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public boolean isIsActive() {
		return this.isActive;
	}

	public void setIsActive(boolean isActive) {
		this.isActive = isActive;
	}

}
