package core.classes.mri;

// default package
// Generated Apr 4, 2015 3:37:57 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * MriEmployee generated by hbm2java
 */
public class MriEmployee implements java.io.Serializable {

	private Integer employeeId;
	private String name;
	private int age;
	private String sex;
	private String address;
	private String contactNo1;
	private String contactNo2;
	private String extension;
	private String email;
	private String nic;
	private boolean isActive;
	private Set mriLaboratories = new HashSet(0);
	private Set mriEmployeeWorkins = new HashSet(0);
	private Set mriDepartments = new HashSet(0);
	private Set mriUsers = new HashSet(0);

	public MriEmployee() {
	}

	public MriEmployee(String name, int age, String sex, String address,
			String contactNo1, String contactNo2, String extension,
			String email, String nic, boolean isActive) {
		this.name = name;
		this.age = age;
		this.sex = sex;
		this.address = address;
		this.contactNo1 = contactNo1;
		this.contactNo2 = contactNo2;
		this.extension = extension;
		this.email = email;
		this.nic = nic;
		this.isActive = isActive;
	}

	public MriEmployee(String name, int age, String sex, String address,
			String contactNo1, String contactNo2, String extension,
			String email, String nic, boolean isActive, Set mriLaboratories,
			Set mriEmployeeWorkins, Set mriDepartments, Set mriUsers) {
		this.name = name;
		this.age = age;
		this.sex = sex;
		this.address = address;
		this.contactNo1 = contactNo1;
		this.contactNo2 = contactNo2;
		this.extension = extension;
		this.email = email;
		this.nic = nic;
		this.isActive = isActive;
		this.mriLaboratories = mriLaboratories;
		this.mriEmployeeWorkins = mriEmployeeWorkins;
		this.mriDepartments = mriDepartments;
		this.mriUsers = mriUsers;
	}

	public Integer getEmployeeId() {
		return this.employeeId;
	}

	public void setEmployeeId(Integer employeeId) {
		this.employeeId = employeeId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public int getAge() {
		return this.age;
	}

	public void setAge(int age) {
		this.age = age;
	}

	public String getSex() {
		return this.sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getContactNo1() {
		return this.contactNo1;
	}

	public void setContactNo1(String contactNo1) {
		this.contactNo1 = contactNo1;
	}

	public String getContactNo2() {
		return this.contactNo2;
	}

	public void setContactNo2(String contactNo2) {
		this.contactNo2 = contactNo2;
	}

	public String getExtension() {
		return this.extension;
	}

	public void setExtension(String extension) {
		this.extension = extension;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getNic() {
		return this.nic;
	}

	public void setNic(String nic) {
		this.nic = nic;
	}

	public boolean isIsActive() {
		return this.isActive;
	}

	public void setIsActive(boolean isActive) {
		this.isActive = isActive;
	}

	public Set getMriLaboratories() {
		return this.mriLaboratories;
	}

	public void setMriLaboratories(Set mriLaboratories) {
		this.mriLaboratories = mriLaboratories;
	}

	public Set getMriEmployeeWorkins() {
		return this.mriEmployeeWorkins;
	}

	public void setMriEmployeeWorkins(Set mriEmployeeWorkins) {
		this.mriEmployeeWorkins = mriEmployeeWorkins;
	}

	public Set getMriDepartments() {
		return this.mriDepartments;
	}

	public void setMriDepartments(Set mriDepartments) {
		this.mriDepartments = mriDepartments;
	}

	public Set getMriUsers() {
		return this.mriUsers;
	}

	public void setMriUsers(Set mriUsers) {
		this.mriUsers = mriUsers;
	}


}
