package core.classes.mri;

// default package
// Generated Apr 4, 2015 3:37:57 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * MriHospital generated by hbm2java
 */
public class MriHospital implements java.io.Serializable {

	private Integer hospitalId;
	private String hospitalName;
	private String address;
	private String location;
	private String contactNo1;
	private String contactNo2;
	private Set mriBundles = new HashSet(0);
	private Set mriHospitalPatients = new HashSet(0);

	public MriHospital() {
	}

	public MriHospital(String hospitalName, String address, String location,
			String contactNo1, String contactNo2) {
		this.hospitalName = hospitalName;
		this.address = address;
		this.location = location;
		this.contactNo1 = contactNo1;
		this.contactNo2 = contactNo2;
	}

	public MriHospital(String hospitalName, String address, String location,
			String contactNo1, String contactNo2, Set mriBundles,
			Set mriHospitalPatients) {
		this.hospitalName = hospitalName;
		this.address = address;
		this.location = location;
		this.contactNo1 = contactNo1;
		this.contactNo2 = contactNo2;
		this.mriBundles = mriBundles;
		this.mriHospitalPatients = mriHospitalPatients;
	}

	public Integer getHospitalId() {
		return this.hospitalId;
	}

	public void setHospitalId(Integer hospitalId) {
		this.hospitalId = hospitalId;
	}

	public String getHospitalName() {
		return this.hospitalName;
	}

	public void setHospitalName(String hospitalName) {
		this.hospitalName = hospitalName;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getLocation() {
		return this.location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

	public String getContactNo1() {
		return this.contactNo1;
	}

	public void setContactNo1(String contactNo1) {
		this.contactNo1 = contactNo1;
	}

	public String getContactNo2() {
		return this.contactNo2;
	}

	public void setContactNo2(String contactNo2) {
		this.contactNo2 = contactNo2;
	}

	public Set getMriBundles() {
		return this.mriBundles;
	}

	public void setMriBundles(Set mriBundles) {
		this.mriBundles = mriBundles;
	}

	public Set getMriHospitalPatients() {
		return this.mriHospitalPatients;
	}

	public void setMriHospitalPatients(Set mriHospitalPatients) {
		this.mriHospitalPatients = mriHospitalPatients;
	}

}
