package core.classes.mri;

// default package
// Generated Apr 4, 2015 3:37:57 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * MriHospitalPatient generated by hbm2java
 */
public class MriHospitalPatient implements java.io.Serializable {

	private Integer hospitalPatientId;
	private MriHospital mriHospital;
	private MriPatient mriPatient;
	private String bhtNo;
	private String ward;
	private Set mriTestRequests = new HashSet(0);

	public MriHospitalPatient() {
	}

	public MriHospitalPatient(MriHospital mriHospital, MriPatient mriPatient,
			String bhtNo, String ward) {
		this.mriHospital = mriHospital;
		this.mriPatient = mriPatient;
		this.bhtNo = bhtNo;
		this.ward = ward;
	}

	public MriHospitalPatient(MriHospital mriHospital, MriPatient mriPatient,
			String bhtNo, String ward, Set mriTestRequests) {
		this.mriHospital = mriHospital;
		this.mriPatient = mriPatient;
		this.bhtNo = bhtNo;
		this.ward = ward;
		this.mriTestRequests = mriTestRequests;
	}

	public Integer getHospitalPatientId() {
		return this.hospitalPatientId;
	}

	public void setHospitalPatientId(Integer hospitalPatientId) {
		this.hospitalPatientId = hospitalPatientId;
	}

	public MriHospital getMriHospital() {
		return this.mriHospital;
	}

	public void setMriHospital(MriHospital mriHospital) {
		this.mriHospital = mriHospital;
	}

	public MriPatient getMriPatient() {
		return this.mriPatient;
	}

	public void setMriPatient(MriPatient mriPatient) {
		this.mriPatient = mriPatient;
	}

	public String getBhtNo() {
		return this.bhtNo;
	}

	public void setBhtNo(String bhtNo) {
		this.bhtNo = bhtNo;
	}

	public String getWard() {
		return this.ward;
	}

	public void setWard(String ward) {
		this.ward = ward;
	}

	public Set getMriTestRequests() {
		return this.mriTestRequests;
	}

	public void setMriTestRequests(Set mriTestRequests) {
		this.mriTestRequests = mriTestRequests;
	}

}
