package core.classes.mri;

// default package
// Generated Apr 4, 2015 3:37:57 PM by Hibernate Tools 3.4.0.CR1

/**
 * MriExternalPatient generated by hbm2java
 */
public class MriInternalPatient implements java.io.Serializable {

	private Integer internalPatientId;
	private MriPatient mriPatient;
	private String address;
	private String contactNo1;
	private String contactNo2;

	public MriInternalPatient() {
	}

	public MriInternalPatient(MriPatient mriPatient, String address,
			String contactNo1, String contactNo2) {
		this.mriPatient = mriPatient;
		this.address = address;
		this.contactNo1 = contactNo1;
		this.contactNo2 = contactNo2;
	}

	public Integer getInternalPatientId() {
		return this.internalPatientId;
	}

	public void setInternalPatientId(Integer internalPatientId) {
		this.internalPatientId = internalPatientId;
	}

	public MriPatient getMriPatient() {
		return this.mriPatient;
	}

	public void setMriPatient(MriPatient mriPatient) {
		this.mriPatient = mriPatient;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getContactNo1() {
		return this.contactNo1;
	}

	public void setContactNo1(String contactNo1) {
		this.contactNo1 = contactNo1;
	}

	public String getContactNo2() {
		return this.contactNo2;
	}

	public void setContactNo2(String contactNo2) {
		this.contactNo2 = contactNo2;
	}

}
