package core.classes.mri;

// default package
// Generated Apr 4, 2015 3:37:57 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * MriLaboratory generated by hbm2java
 */
public class MriLaboratory implements java.io.Serializable {

	private Integer laboratoryId;
	private MriDepartment mriDepartment;
	private MriEmployee mriEmployee;
	private String laboratoryName;
	private String email;
	private String contactNo1;
	private String contactNo2;
	private Set mriEmployeeWorkins = new HashSet(0);
	private Set mriLaboratoryTests = new HashSet(0);

	public MriLaboratory() {
	}

	public MriLaboratory(MriEmployee mriEmployee, String laboratoryName,
			String contactNo1, String contactNo2) {
		this.mriEmployee = mriEmployee;
		this.laboratoryName = laboratoryName;
		this.contactNo1 = contactNo1;
		this.contactNo2 = contactNo2;
	}

	public MriLaboratory(MriDepartment mriDepartment, MriEmployee mriEmployee,
			String laboratoryName, String email, String contactNo1,
			String contactNo2, Set mriEmployeeWorkins, Set mriLaboratoryTests) {
		this.mriDepartment = mriDepartment;
		this.mriEmployee = mriEmployee;
		this.laboratoryName = laboratoryName;
		this.email = email;
		this.contactNo1 = contactNo1;
		this.contactNo2 = contactNo2;
		this.mriEmployeeWorkins = mriEmployeeWorkins;
		this.mriLaboratoryTests = mriLaboratoryTests;
	}

	public Integer getLaboratoryId() {
		return this.laboratoryId;
	}

	public void setLaboratoryId(Integer laboratoryId) {
		this.laboratoryId = laboratoryId;
	}

	public MriDepartment getMriDepartment() {
		return this.mriDepartment;
	}

	public void setMriDepartment(MriDepartment mriDepartment) {
		this.mriDepartment = mriDepartment;
	}

	public MriEmployee getMriEmployee() {
		return this.mriEmployee;
	}

	public void setMriEmployee(MriEmployee mriEmployee) {
		this.mriEmployee = mriEmployee;
	}

	public String getLaboratoryName() {
		return this.laboratoryName;
	}

	public void setLaboratoryName(String laboratoryName) {
		this.laboratoryName = laboratoryName;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getContactNo1() {
		return this.contactNo1;
	}

	public void setContactNo1(String contactNo1) {
		this.contactNo1 = contactNo1;
	}

	public String getContactNo2() {
		return this.contactNo2;
	}

	public void setContactNo2(String contactNo2) {
		this.contactNo2 = contactNo2;
	}

	public Set getMriEmployeeWorkins() {
		return this.mriEmployeeWorkins;
	}

	public void setMriEmployeeWorkins(Set mriEmployeeWorkins) {
		this.mriEmployeeWorkins = mriEmployeeWorkins;
	}

	public Set getMriLaboratoryTests() {
		return this.mriLaboratoryTests;
	}

	public void setMriLaboratoryTests(Set mriLaboratoryTests) {
		this.mriLaboratoryTests = mriLaboratoryTests;
	}

}
