package core.classes.mri;

// default package
// Generated Apr 4, 2015 3:37:57 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * MriPatient generated by hbm2java
 */
public class MriPatient implements java.io.Serializable {

	private Integer patientId;
	private String name;
	private Date birthday;
	private String sex;
	private String nic;
	private boolean isActive;
	private Set mriHospitalPatients = new HashSet(0);
	private Set mriInternalPatient = new HashSet(0);
	private Set mriTestRequests = new HashSet(0);

	public MriPatient() {
	}

	public MriPatient(String name, Date age, String sex, String nic) {
		this.name = name;
		this.birthday = birthday;
		this.sex = sex;
		this.nic = nic;
	}

	public MriPatient(String name, Date birthday, String sex, String nic,
			Set mriHospitalPatients, Set mriInternalPatients,
			Set mriTestRequests) {
		this.name = name;
		this.birthday = birthday;
		this.sex = sex;
		this.nic = nic;
		this.mriHospitalPatients = mriHospitalPatients;
		this.mriInternalPatient = mriInternalPatients;
		this.mriTestRequests = mriTestRequests;
	}

	public Integer getPatientId() {
		return this.patientId;
	}

	public void setPatientId(Integer patientId) {
		this.patientId = patientId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Date getBirthday() {
		return this.birthday;
	}

	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

	public String getSex() {
		return this.sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	public String getNic() {
		return this.nic;
	}

	public void setNic(String nic) {
		this.nic = nic;
	}
	
	public boolean isIsActive() {
		return this.isActive;
	}

	public void setIsActive(boolean isActive) {
		this.isActive = isActive;
	}

	public Set getMriHospitalPatients() {
		return this.mriHospitalPatients;
	}

	public void setMriHospitalPatients(Set mriHospitalPatients) {
		this.mriHospitalPatients = mriHospitalPatients;
	}

	public Set getMriInternalPatients() {
		return this.mriInternalPatient;
	}

	public void setMriInternalPatients(Set mriInternalPatients) {
		this.mriInternalPatient = mriInternalPatients;
	}

	public Set getMriTestRequests() {
		return this.mriTestRequests;
	}

	public void setMriTestRequests(Set mriTestRequests) {
		this.mriTestRequests = mriTestRequests;
	}

}
