package core.classes.mri;// default package
// Generated Sep 6, 2015 6:20:37 PM by Hibernate Tools 3.4.0.CR1

/**
 * MriSubFieldResult generated by hbm2java
 */
public class MriSubFieldResult implements java.io.Serializable {

	private Integer subResultId;
	private MriTestSubFields mriTestSubFields;
	private MriTestRequest mriTestRequest;
	private String subResultValue;

	public MriSubFieldResult() {
	}

	public MriSubFieldResult(String subResultValue) {
		this.subResultValue = subResultValue;
	}

	public MriSubFieldResult(MriTestSubFields mriTestSubFields,
			MriTestRequest mriTestRequest, String subResultValue) {
		this.mriTestSubFields = mriTestSubFields;
		this.mriTestRequest = mriTestRequest;
		this.subResultValue = subResultValue;
	}

	public Integer getSubResultId() {
		return this.subResultId;
	}

	public void setSubResultId(Integer subResultId) {
		this.subResultId = subResultId;
	}

	public MriTestSubFields getMriTestSubFields() {
		return this.mriTestSubFields;
	}

	public void setMriTestSubFields(MriTestSubFields mriTestSubFields) {
		this.mriTestSubFields = mriTestSubFields;
	}

	public MriTestRequest getMriTestRequest() {
		return this.mriTestRequest;
	}

	public void setMriTestRequest(MriTestRequest mriTestRequest) {
		this.mriTestRequest = mriTestRequest;
	}

	public String getSubResultValue() {
		return this.subResultValue;
	}

	public void setSubResultValue(String subResultValue) {
		this.subResultValue = subResultValue;
	}

}
