package core.classes.mri;

// default package
// Generated Apr 4, 2015 3:37:57 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * MriSpecimenType generated by hbm2java
 */
public class MriSpecimenType implements java.io.Serializable {

	private int specimenTypeId;
	private String specimenName;
	private Set<MriSpecimen> mriSpecimens = new HashSet<MriSpecimen>(0);

	public MriSpecimenType() {
	}

	public MriSpecimenType(int specimenTypeId, String specimenName) {
		this.specimenTypeId = specimenTypeId;
		this.specimenName = specimenName;
	}

	public MriSpecimenType(int specimenTypeId, String specimenName,
			Set<MriSpecimen> mriSpecimens) {
		this.specimenTypeId = specimenTypeId;
		this.specimenName = specimenName;
		this.mriSpecimens = mriSpecimens;
	}

	public int getSpecimenTypeId() {
		return this.specimenTypeId;
	}

	public void setSpecimenTypeId(int specimenTypeId) {
		this.specimenTypeId = specimenTypeId;
	}

	public String getSpecimenName() {
		return this.specimenName;
	}

	public void setSpecimenName(String specimenName) {
		this.specimenName = specimenName;
	}

	public Set<MriSpecimen> getMriSpecimens() {
		return this.mriSpecimens;
	}

	public void setMriSpecimens(Set<MriSpecimen> mriSpecimens) {
		this.mriSpecimens = mriSpecimens;
	}

}
