package core.classes.mri;

// default package
// Generated Apr 4, 2015 3:37:57 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * MriSpecimen generated by hbm2java
 */
public class MriSpecimen implements java.io.Serializable {

	private Integer specimenId;
	private MriSpecimenType mriSpecimenType;
	private String specimenBarcode;
	private String remarks;
	private Date specimenReceivedDate;
	private String specimenCollectedPerson;
	private Date specimenDeliveredDepartmentDate;
	private String storedLocation;
	private String storedOrDestroyed;
	private Set mriTestRequests = new HashSet(0);

	public MriSpecimen() {
	}

	public MriSpecimen(MriSpecimenType mriSpecimenType,
			Date specimenReceivedDate, Date specimenDeliveredDepartmentDate,
			String storedLocation, String storedOrDestroyed) {
		this.mriSpecimenType = mriSpecimenType;
		this.specimenReceivedDate = specimenReceivedDate;
		this.specimenDeliveredDepartmentDate = specimenDeliveredDepartmentDate;
		this.storedLocation = storedLocation;
		this.storedOrDestroyed = storedOrDestroyed;
	}

	public MriSpecimen(MriSpecimenType mriSpecimenType, String specimenBarcode,
			String remarks, Date specimenReceivedDate,
			String specimenCollectedPerson,
			Date specimenDeliveredDepartmentDate, String storedLocation,
			String storedOrDestroyed, Set mriTestRequests) {
		this.mriSpecimenType = mriSpecimenType;
		this.specimenBarcode = specimenBarcode;
		this.remarks = remarks;
		this.specimenReceivedDate = specimenReceivedDate;
		this.specimenCollectedPerson = specimenCollectedPerson;
		this.specimenDeliveredDepartmentDate = specimenDeliveredDepartmentDate;
		this.storedLocation = storedLocation;
		this.storedOrDestroyed = storedOrDestroyed;
		this.mriTestRequests = mriTestRequests;
	}

	public Integer getSpecimenId() {
		return this.specimenId;
	}

	public void setSpecimenId(Integer specimenId) {
		this.specimenId = specimenId;
	}

	public MriSpecimenType getMriSpecimenType() {
		return this.mriSpecimenType;
	}

	public void setMriSpecimenType(MriSpecimenType mriSpecimenType) {
		this.mriSpecimenType = mriSpecimenType;
	}

	public String getSpecimenBarcode() {
		return this.specimenBarcode;
	}

	public void setSpecimenBarcode(String specimenBarcode) {
		this.specimenBarcode = specimenBarcode;
	}

	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	public Date getSpecimenReceivedDate() {
		return this.specimenReceivedDate;
	}

	public void setSpecimenReceivedDate(Date specimenReceivedDate) {
		this.specimenReceivedDate = specimenReceivedDate;
	}

	public String getSpecimenCollectedPerson() {
		return this.specimenCollectedPerson;
	}

	public void setSpecimenCollectedPerson(String specimenCollectedPerson) {
		this.specimenCollectedPerson = specimenCollectedPerson;
	}

	public Date getSpecimenDeliveredDepartmentDate() {
		return this.specimenDeliveredDepartmentDate;
	}

	public void setSpecimenDeliveredDepartmentDate(
			Date specimenDeliveredDepartmentDate) {
		this.specimenDeliveredDepartmentDate = specimenDeliveredDepartmentDate;
	}

	public String getStoredLocation() {
		return this.storedLocation;
	}

	public void setStoredLocation(String storedLocation) {
		this.storedLocation = storedLocation;
	}

	public String getStoredOrDestroyed() {
		return this.storedOrDestroyed;
	}

	public void setStoredOrDestroyed(String storedOrDestroyed) {
		this.storedOrDestroyed = storedOrDestroyed;
	}

	public Set getMriTestRequests() {
		return this.mriTestRequests;
	}

	public void setMriTestRequests(Set mriTestRequests) {
		this.mriTestRequests = mriTestRequests;
	}

}
