package core.classes.mri;// default package
// Generated Sep 6, 2015 6:20:37 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * MriTestSubFields generated by hbm2java
 */
public class MriTestSubFields implements java.io.Serializable {

	private Integer testSubFieldId;
	private MriTestParentFields mriTestParentFields;
	private String testSubFieldName;
	private Set mriSubFieldResults = new HashSet(0);
	private Set mriTestSubFieldRanges = new HashSet(0);

	public MriTestSubFields() {
	}

	public MriTestSubFields(MriTestParentFields mriTestParentFields,
			String testSubFieldName) {
		this.mriTestParentFields = mriTestParentFields;
		this.testSubFieldName = testSubFieldName;
	}

	public MriTestSubFields(MriTestParentFields mriTestParentFields,
			String testSubFieldName, Set mriSubFieldResults,
			Set mriTestSubFieldRanges) {
		this.mriTestParentFields = mriTestParentFields;
		this.testSubFieldName = testSubFieldName;
		this.mriSubFieldResults = mriSubFieldResults;
		this.mriTestSubFieldRanges = mriTestSubFieldRanges;
	}

	public Integer getTestSubFieldId() {
		return this.testSubFieldId;
	}

	public void setTestSubFieldId(Integer testSubFieldId) {
		this.testSubFieldId = testSubFieldId;
	}

	public MriTestParentFields getMriTestParentFields() {
		return this.mriTestParentFields;
	}

	public void setMriTestParentFields(MriTestParentFields mriTestParentFields) {
		this.mriTestParentFields = mriTestParentFields;
	}

	public String getTestSubFieldName() {
		return this.testSubFieldName;
	}

	public void setTestSubFieldName(String testSubFieldName) {
		this.testSubFieldName = testSubFieldName;
	}

	public Set getMriSubFieldResults() {
		return this.mriSubFieldResults;
	}

	public void setMriSubFieldResults(Set mriSubFieldResults) {
		this.mriSubFieldResults = mriSubFieldResults;
	}

	public Set getMriTestSubFieldRanges() {
		return this.mriTestSubFieldRanges;
	}

	public void setMriTestSubFieldRanges(Set mriTestSubFieldRanges) {
		this.mriTestSubFieldRanges = mriTestSubFieldRanges;
	}

}
