package core.classes.mri;// default package
// Generated Sep 6, 2015 6:20:37 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * MriTestParentFields generated by hbm2java
 */
public class MriTestParentFields implements java.io.Serializable {

	private Integer testParentFieldId;
	private MriLaboratoryTest mriLaboratoryTest;
	private String testParentFieldName;
	private Set mriTestSubFieldses = new HashSet(0);
	private Set mriParentResults = new HashSet(0);

	public MriTestParentFields() {
	}

	public MriTestParentFields(MriLaboratoryTest mriLaboratoryTest,
			String testParentFieldName) {
		this.mriLaboratoryTest = mriLaboratoryTest;
		this.testParentFieldName = testParentFieldName;
	}

	public MriTestParentFields(MriLaboratoryTest mriLaboratoryTest,
			String testParentFieldName, Set mriTestSubFieldses,
			Set mriParentResults) {
		this.mriLaboratoryTest = mriLaboratoryTest;
		this.testParentFieldName = testParentFieldName;
		this.mriTestSubFieldses = mriTestSubFieldses;
		this.mriParentResults = mriParentResults;
	}

	public Integer getTestParentFieldId() {
		return this.testParentFieldId;
	}

	public void setTestParentFieldId(Integer testParentFieldId) {
		this.testParentFieldId = testParentFieldId;
	}

	public MriLaboratoryTest getMriLaboratoryTest() {
		return this.mriLaboratoryTest;
	}

	public void setMriLaboratoryTest(MriLaboratoryTest mriLaboratoryTest) {
		this.mriLaboratoryTest = mriLaboratoryTest;
	}

	public String getTestParentFieldName() {
		return this.testParentFieldName;
	}

	public void setTestParentFieldName(String testParentFieldName) {
		this.testParentFieldName = testParentFieldName;
	}

	public Set getMriTestSubFieldses() {
		return this.mriTestSubFieldses;
	}

	public void setMriTestSubFieldses(Set mriTestSubFieldses) {
		this.mriTestSubFieldses = mriTestSubFieldses;
	}

	public Set getMriParentResults() {
		return this.mriParentResults;
	}

	public void setMriParentResults(Set mriParentResults) {
		this.mriParentResults = mriParentResults;
	}

}
