package core.classes.mri;

// default package
// Generated Apr 4, 2015 3:37:57 PM by Hibernate Tools 3.4.0.CR1

/**
 * MriTestResultId generated by hbm2java
 */
public class MriTestResultId implements java.io.Serializable {

	private int testResultId;
	private int ftestParentFieldId;

	public MriTestResultId() {
	}

	public MriTestResultId(int testResultId, int ftestParentFieldId) {
		this.testResultId = testResultId;
		this.ftestParentFieldId = ftestParentFieldId;
	}

	public int getTestResultId() {
		return this.testResultId;
	}

	public void setTestResultId(int testResultId) {
		this.testResultId = testResultId;
	}

	public int getFtestParentFieldId() {
		return this.ftestParentFieldId;
	}

	public void setFtestParentFieldId(int ftestParentFieldId) {
		this.ftestParentFieldId = ftestParentFieldId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MriTestResultId))
			return false;
		MriTestResultId castOther = (MriTestResultId) other;

		return (this.getTestResultId() == castOther.getTestResultId())
				&& (this.getFtestParentFieldId() == castOther
						.getFtestParentFieldId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getTestResultId();
		result = 37 * result + this.getFtestParentFieldId();
		return result;
	}

}
