package core.classes.mri;

// default package
// Generated Apr 4, 2015 3:37:57 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * MriTestResult generated by hbm2java
 */
public class MriTestResult implements java.io.Serializable {

	private MriTestResultId id;
	private MriParentResult mriParentResult;
	private MriTestParentFields mriTestParentFields;
	private MriTestRequest mriTestRequest;
	private Date resultFinalizedDate;

	public MriTestResult() {
	}

	public MriTestResult(MriTestResultId id, MriParentResult mriParentResult,
			MriTestParentFields mriTestParentFields, Date resultFinalizedDate) {
		this.id = id;
		this.mriParentResult = mriParentResult;
		this.mriTestParentFields = mriTestParentFields;
		this.resultFinalizedDate = resultFinalizedDate;
	}

	public MriTestResult(MriTestResultId id, MriParentResult mriParentResult,
			MriTestParentFields mriTestParentFields,
			MriTestRequest mriTestRequest, Date resultFinalizedDate) {
		this.id = id;
		this.mriParentResult = mriParentResult;
		this.mriTestParentFields = mriTestParentFields;
		this.mriTestRequest = mriTestRequest;
		this.resultFinalizedDate = resultFinalizedDate;
	}

	public MriTestResultId getId() {
		return this.id;
	}

	public void setId(MriTestResultId id) {
		this.id = id;
	}

	public MriParentResult getMriParentResult() {
		return this.mriParentResult;
	}

	public void setMriParentResult(MriParentResult mriParentResult) {
		this.mriParentResult = mriParentResult;
	}

	public MriTestParentFields getMriTestParentFields() {
		return this.mriTestParentFields;
	}

	public void setMriTestParentFields(MriTestParentFields mriTestParentFields) {
		this.mriTestParentFields = mriTestParentFields;
	}

	public MriTestRequest getMriTestRequest() {
		return this.mriTestRequest;
	}

	public void setMriTestRequest(MriTestRequest mriTestRequest) {
		this.mriTestRequest = mriTestRequest;
	}

	public Date getResultFinalizedDate() {
		return this.resultFinalizedDate;
	}

	public void setResultFinalizedDate(Date resultFinalizedDate) {
		this.resultFinalizedDate = resultFinalizedDate;
	}

}
