package core.classes.mri;// default package
// Generated Sep 6, 2015 6:20:37 PM by Hibernate Tools 3.4.0.CR1

/**
 * MriTestParentFieldRange generated by hbm2java
 */
public class MriTestParentFieldRange implements java.io.Serializable {

	private Integer testParentFieldRangeId;
	private String gender;
	private int minage;
	private String unit;
	private double minVal;
	private double maxVal;
	private Integer maxAge;
	private Integer ftestParentFieldId;

	public MriTestParentFieldRange() {
	}

	public MriTestParentFieldRange(String gender, int minage, double minVal,
			double maxVal) {
		this.gender = gender;
		this.minage = minage;
		this.minVal = minVal;
		this.maxVal = maxVal;
	}

	public MriTestParentFieldRange(String gender, int minage, String unit,
			double minVal, double maxVal, Integer maxAge,
			Integer ftestParentFieldId) {
		this.gender = gender;
		this.minage = minage;
		this.unit = unit;
		this.minVal = minVal;
		this.maxVal = maxVal;
		this.maxAge = maxAge;
		this.ftestParentFieldId = ftestParentFieldId;
	}

	public Integer getTestParentFieldRangeId() {
		return this.testParentFieldRangeId;
	}

	public void setTestParentFieldRangeId(Integer testParentFieldRangeId) {
		this.testParentFieldRangeId = testParentFieldRangeId;
	}

	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	public int getMinage() {
		return this.minage;
	}

	public void setMinage(int minage) {
		this.minage = minage;
	}

	public String getUnit() {
		return this.unit;
	}

	public void setUnit(String unit) {
		this.unit = unit;
	}

	public double getMinVal() {
		return this.minVal;
	}

	public void setMinVal(double minVal) {
		this.minVal = minVal;
	}

	public double getMaxVal() {
		return this.maxVal;
	}

	public void setMaxVal(double maxVal) {
		this.maxVal = maxVal;
	}

	public Integer getMaxAge() {
		return this.maxAge;
	}

	public void setMaxAge(Integer maxAge) {
		this.maxAge = maxAge;
	}

	public Integer getFtestParentFieldId() {
		return this.ftestParentFieldId;
	}

	public void setFtestParentFieldId(Integer ftestParentFieldId) {
		this.ftestParentFieldId = ftestParentFieldId;
	}

}
