package core.classes.mri;

// default package
// Generated Apr 4, 2015 3:37:57 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * MriUserRoles generated by hbm2java
 */
public class MriUserRoles implements java.io.Serializable {

	private int roleId;
	private String roleName;
	private boolean isActive;
	private Set mriUsers = new HashSet(0);

	public MriUserRoles() {
	}

	public MriUserRoles(int roleId, String roleName, boolean isActive) {
		this.roleId = roleId;
		this.roleName = roleName;
		this.isActive = isActive;
	}

	public MriUserRoles(int roleId, String roleName, boolean isActive,
			Set mriUsers) {
		this.roleId = roleId;
		this.roleName = roleName;
		this.isActive = isActive;
		this.mriUsers = mriUsers;
	}

	public int getRoleId() {
		return this.roleId;
	}

	public void setRoleId(int roleId) {
		this.roleId = roleId;
	}

	public String getRoleName() {
		return this.roleName;
	}

	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

	public boolean isIsActive() {
		return this.isActive;
	}

	public void setIsActive(boolean isActive) {
		this.isActive = isActive;
	}

	public Set getMriUsers() {
		return this.mriUsers;
	}

	public void setMriUsers(Set mriUsers) {
		this.mriUsers = mriUsers;
	}

}
