package core.classes.mri;

// default package
// Generated Apr 4, 2015 3:37:57 PM by Hibernate Tools 3.4.0.CR1

/**
 * MriUser generated by hbm2java
 */
public class MriUser implements java.io.Serializable {

	private Integer userId;
	private MriEmployee mriEmployee;
	private MriUserRoles mriUserRoles;
	private String userName;
	private String password;
	private boolean isActive;

	public MriUser() {
	}

	public MriUser(MriEmployee mriEmployee, MriUserRoles mriUserRoles,
			String userName, String password, boolean isActive) {
		this.mriEmployee = mriEmployee;
		this.mriUserRoles = mriUserRoles;
		this.userName = userName;
		this.password = password;
		this.isActive = isActive;
	}

	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public MriEmployee getMriEmployee() {
		return this.mriEmployee;
	}

	public void setMriEmployee(MriEmployee mriEmployee) {
		this.mriEmployee = mriEmployee;
	}

	public MriUserRoles getMriUserRoles() {
		return this.mriUserRoles;
	}

	public void setMriUserRoles(MriUserRoles mriUserRoles) {
		this.mriUserRoles = mriUserRoles;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public boolean isIsActive() {
		return this.isActive;
	}

	public void setIsActive(boolean isActive) {
		this.isActive = isActive;
	}

}
